Fix ethers v5 target incorrect type generated for struct array array
dethcrypto/TypeChain pull request #647
Opened 2022-03-11 21:21 UTC by zemse

2022-03-12 10:57 UTC, krzkaczor commented
I think this implementation is acceptable but we should consider parsing nested types in the TypeChain core, to make targets simpler.

2022-03-12 12:42 UTC, krzkaczor requested changes

2022-03-12 12:42 UTC, krzkaczor commented on packages/target-ethers-v5/src/codegen/types.ts
> +function generateArrayOrTupleType(item: string, originalType: string): string {
I think all of this should be moved to `parseEvmType` directly in TypeChain core.

2022-03-12 12:45 UTC, krzkaczor commented
Also take a look at the implementation in truffle target b/c it's very clean and recursive.

2022-03-12 16:22 UTC, zemse commented
I've refactored the code and the existing tests pass. As a summary of the changes:

- In the typechain package, struct types without structName were being registered. So the `fix` commit [7289bbd](https://github.com/dethcrypto/TypeChain/pull/647/commits/7289bbdb9c6faed74d4afb0e34d4dfdaa38c3487) simply adds a check in registerStruct function (inside abiParser file) to skip such struct from registering.
- Struct with "array" type was being registered (when chronologically the array type was being encountered in the ABI), the same "fix" commit adds logic in registerStruct function to go deep and register the "tuple" if an "array" is encountered. Also a problem with this was, `structName` was not set, hence to make this work, "internalType" arg is passed recursively in `parseEvmType` function which sets the `structName` prop for the struct tuple too.
- Fixes ethers v5 test case in struct.test.ts for CallStruct which expects it to be array type. [link](https://github.com/dethcrypto/TypeChain/blob/master/packages/target-ethers-v5/test/structs.test.ts#L53). Here CallStruct is being expected as array.

Finally, the "refactor" commit is able to implement the normal recursive logic which looks cleaner (due to changes in previous commit).

Since these are breaking changes, it would be great if you can have a good enough look (I feel very less confident because I just made changes and it worked in first try lol). I just thought about a test case, will add it right now, just to be sure.

2022-03-16 09:15 UTC, hasparus approved these changes

2022-03-16 09:15 UTC, merged